### ISSUE TITLE
Need to add monokai package to your setup

### ISSUE THREAD

**Issue by kyp0717** [brainfucksec/neovim-lua#1]
Here is the error msg:
vim(colorscheme)185: Cannot find color scheme "monokai"

**Comment by brainfucksec** [comment]
Hi @kyp0717, you need to download the packages in the list with `Paq`:

https://github.com/brainfucksec/neovim-lua#installation

**Comment by RyanGreenup** [comment]
I think the issue is that you can't run `:PaqInstall` on the first startup because the config stops loading after 58: `cmd('colorscheme monokai')` fails.

To get set up you can comment that out on the first start.
