### ISSUE TITLE
vim.g.vista_default_executive = 'nvim_lsp' seems don't work

### ISSUE THREAD

**Issue by chengzhycn** [brainfucksec/neovim-lua#10]
When I comment pcall block in vista.lua and call Vista, it print traceback below:
```
Error executing vim.schedule lua callback: Vim(let):E896: Argument of map() must be a List, Dictionary or Blob
stack traceback:
        [C]: in function 'vista#renderer#LSPProcess'
        [string ":lua"]:20: in function 'handler'
        /usr/local/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

When I comment vista_default_executive config, it works well.
```
-- vim.g.vista_default_executive = 'nvim_lsp'
```

Have I misunderstood or misconfiged something?

**Comment by brainfucksec** [comment]
Hi @chengzhycn 
From the path I read "nvim-osx64", please note that this setup has been tested on GNU/Linux and Windows systems and not on macOS.
Anyway, to use Vista you have to install `ctags` if you haven't already done so, If you have it installed try to use `ctags` as executive, if you don't get any error then the problem could be nvim_lsp on macOS.

```vim
" Executive used when opening vista sidebar without specifying it.
" See all the avaliable executives via `:echo g:vista#executives`.
let g:vista_default_executive = 'ctags'
```

See: https://github.com/liuchengxu/vista.vim#options

**Comment by chengzhycn** [comment]
@brainfucksec Hi, thanks for your reply.

I tested on Linux(centos 7) and it also could not work.
```
Error executing vim.schedule lua callback: Vim(let):E896: Argument of map() must be a List, Dictionary or Blob
stack traceback:
        [C]: in function 'vista#renderer#LSPProcess'
        [string ":lua"]:20: in function 'handler'
        ....mount_nvimDX00Tv/usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```
I do not use windows as my dev environment so I can't test it on windows. As far as I can see, setting `vista_default_executive` to `nvim_lsp` would cause vista to fail when working both on linux and mac. When using default `vista_default_executive`, it works well with no error. I viewed the trace, it seems error happens when called `vim.lsp.buf_request`.

**Comment by chengzhycn** [comment]
@brainfucksec Hi, I finally found the problem config:
```
vim.g.vista_icon_indent = '["╰─▸ ", "├─▸ "]'
```
from the help file, we can see it should be a List type. So this config should be modified to this:
```
vim.g.vista_icon_indent = {"╰─▸ ", "├─▸ "}
```
And it works at all.
Thanks for your excellent nvim config, I learnt a lot from it :).

**Comment by brainfucksec** [comment]
Thank you for the hint, I will correct the error :)
Anyway I'm thinking of going back to [tagbar](https://github.com/preservim/tagbar)

**Comment by brainfucksec** [comment]
Fix (workaround) ..for now, see: [9b5c28e](https://github.com/brainfucksec/neovim-lua/commit/9b5c28e0c57b2ead9361dddca2e4f3a8f6e12047) 

The changes on the icons seem to have no effect, the plugin seems to suffer some incompatibilities, I think the right thing is to go back to tagbar, thanks again for the hint.

**Comment by brainfucksec** [comment]
Ok, [replaced Vista with Tagbar](https://github.com/brainfucksec/neovim-lua/commit/f780f17245af42616c0be4ff73517ab207d30727)

Since support of LSP diagnostic doesn't seem essential on the side view (at least for me), I decided to switch to Tagbar, it opens faster and the way it sorts the tags provides a better experience, also the plugin is updated and maintained.

**Comment by chengzhycn** [comment]
> Fix (workaround) ..for now, see: [9b5c28e](https://github.com/brainfucksec/neovim-lua/commit/9b5c28e0c57b2ead9361dddca2e4f3a8f6e12047)
> 
> The changes on the icons seem to have no effect, the plugin seems to suffer some incompatibilities, I think the right thing is to go back to tagbar, thanks again for the hint.

~~@brainfucksec It works for me. But this config may only work for LSP executives, not for ctags. See help file:~~
```
g:vista_icon_indent                                          g:vista_icon_indent

  Type: List
  Default: ['└ ', '│ ']

  How each level is indented and what to prepend. This could make
  the display more compact or more spacious.

  Note: this option only works the LSP executives, doesn't work for :Vista ctags .
```

**Comment by chengzhycn** [comment]
Sorry, I misunderstood your comments. You are right, when starting nvim, the `g:vista#renderer#icons`'s config is the same as in the vista.lua. But when toggled the vista, the configuration was rewritten to the default.
