### ISSUE TITLE
readme fork

### ISSUE THREAD

**Issue by ghost** [brainfucksec/neovim-lua#12]
i modified your readme to make my own neovim configuration repo []() https://gitlab.com/elai1/luavim.git is that okay?

**Comment by brainfucksec** [comment]
Hi @micro-aries 
Obviously that's fine, that's the purpose of my shares, glad you found it helpful.
Thanks to you for the reference in the README.

**Comment by ghost** [comment]
thank you i really appreciate it, about the reference it's  the least that i can do, your configs helped me a alot
