### ISSUE TITLE
Some lspconfig keymaps not working

### ISSUE THREAD

**Issue by ggteixeira** [brainfucksec/neovim-lua#13]
Hi! First of all, congrats for your project. I'm currently migrating from Vimscript to Lua using mostly your repo as a template! It works pretty well out of the box!

However, if you don't mind, could you help me understand why some lspconfig keymaps aren't working? Keymaps such as: `  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)`, for example.

It's a weird behavior because they do work if I call them manually; but doesn't work whenever I call them by the keymap provided by lspconfig. 

Do you have any hints? Sorry for using your issues sections; it was the less intrusive way to contact you

**Comment by ggteixeira** [comment]
UPDATED: I just uninstalled and installed again some servers using `lspinstall` and suddenly it started working. Magic happens!

**Comment by brainfucksec** [comment]
However, the keymaps configuration for nvim-lspconfig can be found in the `nvim/lua/core/plugins/nvim-lspconfig.lua` and not in the `nvim/lua/core/keymaps.lua`, the keys are the defaults shown in the [nvim-lspconfig wiki](https://github.com/neovim/nvim-lspconfig/wiki/Complete-init.lua-example).
Also this plugin is constantly evolving, you should check this wiki sometimes :)

**Comment by ggteixeira** [comment]
I'll make sure my configs are constantly updated! Thank you for the tips!

**Comment by brainfucksec** [comment]
You're welcome. good work.
