### ISSUE TITLE
Bootstrap Need to Update for the First Run

### ISSUE THREAD

**Issue by runleik** [brainfucksec/neovim-lua#16]
Hi Sir,

I am writting to report an issue in your configuration file '_packer_init.lua_' that _vim.fn.stdpath('data') .. '/site/pack/*/start/*'_ is not added to the runtime path if the site directory is not exited in the new version when the first running.

Please kindly refer to this issue '[_Bootstrapping doesn't work #750_](https://github.com/wbthomason/packer.nvim/issues/750)'.

**Comment by brainfucksec** [comment]
Hi @runleik, fixed, thanks for the advice.
See: [Fix packer boostrap](https://github.com/brainfucksec/neovim-lua/commit/74c65ddb50be7aaf587bb7c84feccc3ab76a3c5d)
