### ISSUE TITLE
Ability to set settings for LSP servers

### ISSUE THREAD

**Issue by ryanwalder** [brainfucksec/neovim-lua#20]
I'm a little lost in how to apply settings to the lspconfig of a specific language server. I understand `yamlls` isn't supported by the repo but I think the solution would work with all servers.

For example, if I wanted to add the following settings for the `yamlls` server I'm not sure how to go about this as I'm a LUA noob

```
	settings = {
		yaml = {
			format = { enable = true, singleQuote = true },
			validate = true,
			hover = true,
			completion = true,
			schemaStore = {
				enable = true,
				url = 'https://www.schemastore.org/api/json/catalog.json',
			},
			schemas = {
				kubernetes = {
					'helm/**/templates/**/*.yaml',
					'kube/**/*.yaml',
				},
				['https://json.schemastore.org/github-workflow.json'] = '.github/workflows/*.{yml,yaml}',
				['https://json.schemastore.org/github-action.json'] = '.github/action.{yml,yaml}',
				['https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json'] = '/*lab-ci.{yml,yaml}',
				['https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json'] = 'roles/tasks/**/*.{yml,yaml}',
				['https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json'] = 'playbook{s,}/**/*.{yml,yaml}',
				['https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-inventory.json'] = 'inventory/*.{ini,yml}',
				['https://json.schemastore.org/prettierrc.json'] = '.prettierrc.{yml,yaml}',
				['https://json.schemastore.org/stylelintrc.json'] = '.stylelintrc.{yml,yaml}',
				['https://json.schemastore.org/circleciconfig'] = '.circleci/**/*.{yml,yaml}',
				['https://json.schemastore.org/kustomization'] = 'kustomization.{yml,yaml}',
				['https://json.schemastore.org/helmfile'] = 'helmfile.{yml,yaml}',
			},
		},
	},
```

I have `yamlls` in `servers` in `nvim/lua/plugins/nvim-lspconfig.lua` and it installs/works perfectly, just without any settings.

I was thinking something along the lines of a `plugins/lsp/$servername.lua` which could contain the settings then be referenced in some way during the `for _, lsp in ipairs(servers) do` loop and grabbing the settings from that file if present in a `settings` variable or something. But I'm a little lost on how this could be implemented.

**Comment by brainfucksec** [comment]
Hi @ryanwalder, try to put the settings for a language server into a variable and call it within the setup function, for example:

```lua
yaml_settings = { your_settings_here },

-- Call setup
for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    root_dir = root_dir,
    capabilities = capabilities,
    yaml_settings = yaml_settings,
    flags = {
      -- default in neovim 0.7+
      debounce_text_changes = 150,
    }
  }
end
```

Or, as you said, for a modular configuration, you can create an `lsp` folder and inside it put a `yaml.lua` file with your settings and then call the module in the `nvim-lspconfig.lua` file, look at this configuration as an example: 

https://github.com/LunarVim/Neovim-from-scratch

**Comment by ryanwalder** [comment]
Ah I think I see how to do it now, thanks for the Neovim-from-scratch example, that helps immensely. Also thanks for your work, this is a great base to build off!

**Comment by brainfucksec** [comment]
@ryanwalder I hope this is the right solution and I'm glad the config is helpful :)
