### ISSUE TITLE
Input delay caused by insert mode <leader> mapping 

### ISSUE THREAD

**Issue by carzum** [brainfucksec/neovim-lua#22]
The single insert mode leader key mapping  (https://github.com/brainfucksec/neovim-lua/blob/main/nvim/lua/core/keymaps.lua#L51) is causing a noticeable delay before the leader character is rendered. This can be quite annoying, as common leader choices like comma and space are also used often in code.
Removing the key mapping speeds up rendering and feels like the 'saner' default mapping.

**Comment by brainfucksec** [comment]
Thanks for reporting, I will do a research on this topic.

**Comment by carzum** [comment]
Its caused by the fast saving keymap, vim will wait 1000ms for the mapped sequence to complete and then render the leader key (:h timeoutlen)
https://github.com/brainfucksec/neovim-lua/blob/068e42a6f63645b0c51986a2f173511a62df5616/nvim/lua/core/keymaps.lua#L51

Others might not be bothered by it, this could be considered personal preference ;)

**Comment by brainfucksec** [comment]
@carzum, so the culprit is not the leader key but the mapping with `s` to save?

**Comment by brainfucksec** [comment]
I removed the <leader> key mapping in Insert mode for saving.
See: [Fix for issue: 22 (Input delay caused by insert mode <leader> mapping)](https://github.com/brainfucksec/neovim-lua/commit/e7627205b58ba30f4d0546b2a8cd26d0f91f6b87)

Thanks again @carzum :)
