### ISSUE TITLE
Config Breaks on Windows

### ISSUE THREAD

**Issue by BatmiBoom** [brainfucksec/neovim-lua#24]
NVIM v0.9.0-dev-85-gb55742faf

Operating system/version - Windows 11

Terminal -> Powershell 7 -> xterm-256color

1 - When I use any kind of file explorer [ I change nvimTree for another, but it happens with both]
![image](https://user-images.githubusercontent.com/47833971/195968005-a3f119b6-27d2-41d4-a8ff-61976ede49d1.png)

And try to open a file, this happens

![image](https://user-images.githubusercontent.com/47833971/195968014-0b0531b0-1e64-433d-87c4-839f64705560.png)

It happens with any kind of file, doesn't happen all the time

Also when I try to do

```console
nvim file_name.extension
```

It opens and close immediately, no errors, no nothing.

I have the same config in mac, and it works fine, so it has to be a Windwos problem.

2 - The times that it's working and I can open a file, it freezes after 1 / 2 min and I have to close the terminal.

How to reproduce the issue
-  Open nvim
-  Run :PackerSync
-  Open explorer with v
- Move around the explorer open directories, and try to open a file [ any file, a lua file or svelte file or whatever ]
- There is a change that either neovim freezes and you have to close the terminal and open again
 or it will exit automatically and the terminal is gonna end up with part neovim part terminal

**Comment by brainfucksec** [comment]
Hi @batmikun, sorry but these config is not tested/supported on Windows systems :(

**Comment by BatmiBoom** [comment]
Thanks anyway!
