### ISSUE TITLE
Problem calling lua chunk

### ISSUE THREAD

**Issue by testfailagain** [brainfucksec/neovim-lua#3]
Hi,

I don't have good knowledge about lua yet, so, I appreciate the starting point you give me with that clear file tree.
But I have a problem, Maybe I lost one step but I see this error:
`Error detected while processing /home/hugo/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/hugo/.config/nvim/lua/plugins/nvim-tree.lua:34:
 module 'nvim-tree' not found:
        no field package.preload['nvim-tree']
        no file './nvim-tree.lua'
        no file '/usr/share/luajit-2.1.0-beta3/nvim-tree.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/init.lua'
        no file '/usr/share/lua/5.1/nvim-tree.lua'
        no file '/usr/share/lua/5.1/nvim-tree/init.lua'
        no file './nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/hugo/.config/nvim/lua/plugins/nvim-tree.lua:34: in main chunk
        [C]: in function 'require'
        /home/hugo/.config/nvim/init.lua:24: in main chunk
`
First I had it with monokai, then I comment it and I have this error.

What should I do? I miss some installation? or did I need to execute some command like 'PlugInstall'?

**Comment by testfailagain** [comment]
I'm going to give some more info, just in case, I'm using ubuntu 20, and neo-vim:
nvim -v
```
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-Sc2iua/neovim-0.7.0~ubuntu1+git202201220047-e07a4b97f-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-Sc2iua/neovim-0.7.0~ubuntu1+git202201220047-e07a4b97f-dd05b3569/build/config -I/build/neovim-Sc2iua/neovim-0.7.0~ubuntu1+git202201220047-e07a4b97f-dd05b3569/src -I/build/neovim-Sc2iua/neovim-0.7.0~ubuntu1+git202201220047-e07a4b97f-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-Sc2iua/neovim-0.7.0~ubuntu1+git202201220047-e07a4b97f-dd05b3569/build/src/nvim/auto -I/build/neovim-Sc2iua/neovim-0.7.0~ubuntu1+git202201220047-e07a4b97f-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-060

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by brainfucksec** [comment]
Hi @testfailagain, yes, you need to install the plugins with `packer` first:

```bash
:PackerCompile

:PackerUpdate
```

See:  [packer.nvim - Quickstart](https://github.com/wbthomason/packer.nvim#quickstart)
