### ISSUE TITLE
Error when open file

### ISSUE THREAD

**Issue by AhmadNaruto** [brainfucksec/neovim-lua#30]
i try using this and all fine at first but when i open file (example.py) it show error 
honestly I don't know what's happening 

`Error detected while processing /data/data/com.termux/fi
les/home/.config/nvim/init.lua:                         E5113: Error while calling lua chunk: .../share/nvim/laz
y/indent-blankline.nvim/lua/ibl/utils.lua:18: 'buftype_exclude' is not a valid key of ibl.config                stack traceback:                                                [C]: in function 'error'                                .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:18: in function 'validate'                          ...share/nvim/lazy/indent-blankline.nvim/lua/ibl/config.lua:111: in function 'validate_config'                  ...share/nvim/lazy/indent-blankline.nvim/lua/ibl/config.lua:271: in function 'set_config'                       ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:59: in function 'setup'                             ...files/home/.config/nvim/lua/plugins/indent-blankline.lua:14: in main chunk                                   [C]: in function 'require'                              /data/data/com.termux/files/home/.config/nvim/in
it.lua:18: in main chunk`

FYI: i not edit anything, just clone and copy.

**Comment by brainfucksec** [comment]
Hi @AhmadNaruto, You need to update the packages, just use `u` at Homepage for Update all packages with [lazy.nvim](https://github.com/folke/lazy.nvim).

**Comment by brainfucksec** [comment]
Since it’s been long time, I hope things are working well for you now. I’ll close the issue until we can confirm it’s still happening. I’m happy to continue further discussion whenever needed.
