### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by jd84** [brainfucksec/neovim-lua#6]
@brainfucksec 

I just want to say THANKS for sharing the cleanest nvim setup I've ever seen. You made my upgrade from 0.4(1k init.vim) to 0.6 (fresh, clean, lua) so god damn simple!

**Comment by brainfucksec** [comment]
Thank You, I'm glad you find it useful :)

**Comment by ghost** [comment]
Nice and clean config, but `require('packer_init')` line in `init.lua` file needs to be moved to the top when running for the first time, otherwise neovim won't see packer.nvim
